<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class PaisesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	$now = \Carbon\Carbon::now();

        $paises = [
            ["codigo_iso" => "AF", "descripcion" => "Afghanistan"],
            ["codigo_iso" => "AL", "descripcion" => "Albania"],
            ["codigo_iso" => "DZ", "descripcion" => "Algeria"],
            ["codigo_iso" => "DS", "descripcion" => "American Samoa"],
            ["codigo_iso" => "AD", "descripcion" => "Andorra"],
            ["codigo_iso" => "AO", "descripcion" => "Angola"],
            ["codigo_iso" => "AI", "descripcion" => "Anguilla"],
            ["codigo_iso" => "AQ", "descripcion" => "Antarctica"],
            ["codigo_iso" => "AG", "descripcion" => "Antigua and Barbuda"],
            ["codigo_iso" => "AR", "descripcion" => "Argentina"],
            ["codigo_iso" => "AM", "descripcion" => "Armenia"],
            ["codigo_iso" => "AW", "descripcion" => "Aruba"],
            ["codigo_iso" => "AU", "descripcion" => "Australia"],
            ["codigo_iso" => "AT", "descripcion" => "Austria"],
            ["codigo_iso" => "AZ", "descripcion" => "Azerbaijan"],
            ["codigo_iso" => "BS", "descripcion" => "Bahamas"],
            ["codigo_iso" => "BH", "descripcion" => "Bahrain"],
            ["codigo_iso" => "BD", "descripcion" => "Bangladesh"],
            ["codigo_iso" => "BB", "descripcion" => "Barbados"],
            ["codigo_iso" => "BY", "descripcion" => "Belarus"],
            ["codigo_iso" => "BE", "descripcion" => "Belgium"],
            ["codigo_iso" => "BZ", "descripcion" => "Belize"],
            ["codigo_iso" => "BJ", "descripcion" => "Benin"],
            ["codigo_iso" => "BM", "descripcion" => "Bermuda"],
            ["codigo_iso" => "BT", "descripcion" => "Bhutan"],
            ["codigo_iso" => "BO", "descripcion" => "Bolivia"],
            ["codigo_iso" => "BA", "descripcion" => "Bosnia and Herzegovina"],
            ["codigo_iso" => "BW", "descripcion" => "Botswana"],
            ["codigo_iso" => "BV", "descripcion" => "Bouvet Island"],
            ["codigo_iso" => "BR", "descripcion" => "Brazil"],
            ["codigo_iso" => "IO", "descripcion" => "British Indian Ocean Territory"],
            ["codigo_iso" => "BN", "descripcion" => "Brunei Darussalam"],
            ["codigo_iso" => "BG", "descripcion" => "Bulgaria"],
            ["codigo_iso" => "BF", "descripcion" => "Burkina Faso"],
            ["codigo_iso" => "BI", "descripcion" => "Burundi"],
            ["codigo_iso" => "KH", "descripcion" => "Cambodia"],
            ["codigo_iso" => "CM", "descripcion" => "Cameroon"],
            ["codigo_iso" => "CA", "descripcion" => "Canada"],
            ["codigo_iso" => "CV", "descripcion" => "Cape Verde"],
            ["codigo_iso" => "KY", "descripcion" => "Cayman Islands"],
            ["codigo_iso" => "CF", "descripcion" => "Central African Republic"],
            ["codigo_iso" => "TD", "descripcion" => "Chad"],
            ["codigo_iso" => "CL", "descripcion" => "Chile"],
            ["codigo_iso" => "CN", "descripcion" => "China"],
            ["codigo_iso" => "CX", "descripcion" => "Christmas Island"],
            ["codigo_iso" => "CC", "descripcion" => "Cocos (Keeling) Islands"],
            ["codigo_iso" => "CO", "descripcion" => "Colombia"],
            ["codigo_iso" => "KM", "descripcion" => "Comoros"],
            ["codigo_iso" => "CG", "descripcion" => "Congo"],
            ["codigo_iso" => "CK", "descripcion" => "Cook Islands"],
            ["codigo_iso" => "CR", "descripcion" => "Costa Rica"],
            ["codigo_iso" => "HR", "descripcion" => "Croatia (Hrvatska)"],
            ["codigo_iso" => "CU", "descripcion" => "Cuba"],
            ["codigo_iso" => "CY", "descripcion" => "Cyprus"],
            ["codigo_iso" => "CZ", "descripcion" => "Czech Republic"],
            ["codigo_iso" => "DK", "descripcion" => "Denmark"],
            ["codigo_iso" => "DJ", "descripcion" => "Djibouti"],
            ["codigo_iso" => "DM", "descripcion" => "Dominica"],
            ["codigo_iso" => "DO", "descripcion" => "Dominican Republic"],
            ["codigo_iso" => "TP", "descripcion" => "East Timor"],
            ["codigo_iso" => "EC", "descripcion" => "Ecuador"],
            ["codigo_iso" => "EG", "descripcion" => "Egypt"],
            ["codigo_iso" => "SV", "descripcion" => "El Salvador"],
            ["codigo_iso" => "GQ", "descripcion" => "Equatorial Guinea"],
            ["codigo_iso" => "ER", "descripcion" => "Eritrea"],
            ["codigo_iso" => "EE", "descripcion" => "Estonia"],
            ["codigo_iso" => "ET", "descripcion" => "Ethiopia"],
            ["codigo_iso" => "FK", "descripcion" => "Falkland Islands (Malvinas)"],
            ["codigo_iso" => "FO", "descripcion" => "Faroe Islands"],
            ["codigo_iso" => "FJ", "descripcion" => "Fiji"],
            ["codigo_iso" => "FI", "descripcion" => "Finland"],
            ["codigo_iso" => "FR", "descripcion" => "France"],
            ["codigo_iso" => "FX", "descripcion" => "France, Metropolitan"],
            ["codigo_iso" => "GF", "descripcion" => "French Guiana"],
            ["codigo_iso" => "PF", "descripcion" => "French Polynesia"],
            ["codigo_iso" => "TF", "descripcion" => "French Southern Territories"],
            ["codigo_iso" => "GA", "descripcion" => "Gabon"],
            ["codigo_iso" => "GM", "descripcion" => "Gambia"],
            ["codigo_iso" => "GE", "descripcion" => "Georgia"],
            ["codigo_iso" => "DE", "descripcion" => "Germany"],
            ["codigo_iso" => "GH", "descripcion" => "Ghana"],
            ["codigo_iso" => "GI", "descripcion" => "Gibraltar"],
            ["codigo_iso" => "GK", "descripcion" => "Guernsey"],
            ["codigo_iso" => "GR", "descripcion" => "Greece"],
            ["codigo_iso" => "GL", "descripcion" => "Greenland"],
            ["codigo_iso" => "GD", "descripcion" => "Grenada"],
            ["codigo_iso" => "GP", "descripcion" => "Guadeloupe"],
            ["codigo_iso" => "GU", "descripcion" => "Guam"],
            ["codigo_iso" => "GT", "descripcion" => "Guatemala"],
            ["codigo_iso" => "GN", "descripcion" => "Guinea"],
            ["codigo_iso" => "GW", "descripcion" => "Guinea-Bissau"],
            ["codigo_iso" => "GY", "descripcion" => "Guyana"],
            ["codigo_iso" => "HT", "descripcion" => "Haiti"],
            ["codigo_iso" => "HM", "descripcion" => "Heard and Mc Donald Islands"],
            ["codigo_iso" => "HN", "descripcion" => "Honduras"],
            ["codigo_iso" => "HK", "descripcion" => "Hong Kong"],
            ["codigo_iso" => "HU", "descripcion" => "Hungary"],
            ["codigo_iso" => "IS", "descripcion" => "Iceland"],
            ["codigo_iso" => "IN", "descripcion" => "India"],
            ["codigo_iso" => "IM", "descripcion" => "Isle of Man"],
            ["codigo_iso" => "ID", "descripcion" => "Indonesia"],
            ["codigo_iso" => "IR", "descripcion" => "Iran (Islamic Republic of)"],
            ["codigo_iso" => "IQ", "descripcion" => "Iraq"],
            ["codigo_iso" => "IE", "descripcion" => "Ireland"],
            ["codigo_iso" => "IL", "descripcion" => "Israel"],
            ["codigo_iso" => "IT", "descripcion" => "Italy"],
            ["codigo_iso" => "CI", "descripcion" => "Ivory Coast"],
            ["codigo_iso" => "JE", "descripcion" => "Jersey"],
            ["codigo_iso" => "JM", "descripcion" => "Jamaica"],
            ["codigo_iso" => "JP", "descripcion" => "Japan"],
            ["codigo_iso" => "JO", "descripcion" => "Jordan"],
            ["codigo_iso" => "KZ", "descripcion" => "Kazakhstan"],
            ["codigo_iso" => "KE", "descripcion" => "Kenya"],
            ["codigo_iso" => "KI", "descripcion" => "Kiribati"],
            ["codigo_iso" => "KP", "descripcion" => "Korea, Democratic People\'s Republic of"],
            ["codigo_iso" => "KR", "descripcion" => "Korea, Republic of"],
            ["codigo_iso" => "XK", "descripcion" => "Kosovo"],
            ["codigo_iso" => "KW", "descripcion" => "Kuwait"],
            ["codigo_iso" => "KG", "descripcion" => "Kyrgyzstan"],
            ["codigo_iso" => "LA", "descripcion" => "Lao People\'s Democratic Republic"],
            ["codigo_iso" => "LV", "descripcion" => "Latvia"],
            ["codigo_iso" => "LB", "descripcion" => "Lebanon"],
            ["codigo_iso" => "LS", "descripcion" => "Lesotho"],
            ["codigo_iso" => "LR", "descripcion" => "Liberia"],
            ["codigo_iso" => "LY", "descripcion" => "Libyan Arab Jamahiriya"],
            ["codigo_iso" => "LI", "descripcion" => "Liechtenstein"],
            ["codigo_iso" => "LT", "descripcion" => "Lithuania"],
            ["codigo_iso" => "LU", "descripcion" => "Luxembourg"],
            ["codigo_iso" => "MO", "descripcion" => "Macau"],
            ["codigo_iso" => "MK", "descripcion" => "Macedonia"],
            ["codigo_iso" => "MG", "descripcion" => "Madagascar"],
            ["codigo_iso" => "MW", "descripcion" => "Malawi"],
            ["codigo_iso" => "MY", "descripcion" => "Malaysia"],
            ["codigo_iso" => "MV", "descripcion" => "Maldives"],
            ["codigo_iso" => "ML", "descripcion" => "Mali"],
            ["codigo_iso" => "MT", "descripcion" => "Malta"],
            ["codigo_iso" => "MH", "descripcion" => "Marshall Islands"],
            ["codigo_iso" => "MQ", "descripcion" => "Martinique"],
            ["codigo_iso" => "MR", "descripcion" => "Mauritania"],
            ["codigo_iso" => "MU", "descripcion" => "Mauritius"],
            ["codigo_iso" => "TY", "descripcion" => "Mayotte"],
            ["codigo_iso" => "MX", "descripcion" => "Mexico"],
            ["codigo_iso" => "FM", "descripcion" => "Micronesia, Federated States of"],
            ["codigo_iso" => "MD", "descripcion" => "Moldova, Republic of"],
            ["codigo_iso" => "MC", "descripcion" => "Monaco"],
            ["codigo_iso" => "MN", "descripcion" => "Mongolia"],
            ["codigo_iso" => "ME", "descripcion" => "Montenegro"],
            ["codigo_iso" => "MS", "descripcion" => "Montserrat"],
            ["codigo_iso" => "MA", "descripcion" => "Morocco"],
            ["codigo_iso" => "MZ", "descripcion" => "Mozambique"],
            ["codigo_iso" => "MM", "descripcion" => "Myanmar"],
            ["codigo_iso" => "NA", "descripcion" => "Namibia"],
            ["codigo_iso" => "NR", "descripcion" => "Nauru"],
            ["codigo_iso" => "NP", "descripcion" => "Nepal"],
            ["codigo_iso" => "NL", "descripcion" => "Netherlands"],
            ["codigo_iso" => "AN", "descripcion" => "Netherlands Antilles"],
            ["codigo_iso" => "NC", "descripcion" => "New Caledonia"],
            ["codigo_iso" => "NZ", "descripcion" => "New Zealand"],
            ["codigo_iso" => "NI", "descripcion" => "Nicaragua"],
            ["codigo_iso" => "NE", "descripcion" => "Niger"],
            ["codigo_iso" => "NG", "descripcion" => "Nigeria"],
            ["codigo_iso" => "NU", "descripcion" => "Niue"],
            ["codigo_iso" => "NF", "descripcion" => "Norfolk Island"],
            ["codigo_iso" => "MP", "descripcion" => "Northern Mariana Islands"],
            ["codigo_iso" => "NO", "descripcion" => "Norway"],
            ["codigo_iso" => "OM", "descripcion" => "Oman"],
            ["codigo_iso" => "PK", "descripcion" => "Pakistan"],
            ["codigo_iso" => "PW", "descripcion" => "Palau"],
            ["codigo_iso" => "PS", "descripcion" => "Palestine"],
            ["codigo_iso" => "PA", "descripcion" => "Panama"],
            ["codigo_iso" => "PG", "descripcion" => "Papua New Guinea"],
            ["codigo_iso" => "PY", "descripcion" => "Paraguay"],
            ["codigo_iso" => "PE", "descripcion" => "Peru"],
            ["codigo_iso" => "PH", "descripcion" => "Philippines"],
            ["codigo_iso" => "PN", "descripcion" => "Pitcairn"],
            ["codigo_iso" => "PL", "descripcion" => "Poland"],
            ["codigo_iso" => "PT", "descripcion" => "Portugal"],
            ["codigo_iso" => "PR", "descripcion" => "Puerto Rico"],
            ["codigo_iso" => "QA", "descripcion" => "Qatar"],
            ["codigo_iso" => "RE", "descripcion" => "Reunion"],
            ["codigo_iso" => "RO", "descripcion" => "Romania"],
            ["codigo_iso" => "RU", "descripcion" => "Russian Federation"],
            ["codigo_iso" => "RW", "descripcion" => "Rwanda"],
            ["codigo_iso" => "KN", "descripcion" => "Saint Kitts and Nevis"],
            ["codigo_iso" => "LC", "descripcion" => "Saint Lucia"],
            ["codigo_iso" => "VC", "descripcion" => "Saint Vincent and the Grenadines"],
            ["codigo_iso" => "WS", "descripcion" => "Samoa"],
            ["codigo_iso" => "SM", "descripcion" => "San Marino"],
            ["codigo_iso" => "ST", "descripcion" => "Sao Tome and Principe"],
            ["codigo_iso" => "SA", "descripcion" => "Saudi Arabia"],
            ["codigo_iso" => "SN", "descripcion" => "Senegal"],
            ["codigo_iso" => "RS", "descripcion" => "Serbia"],
            ["codigo_iso" => "SC", "descripcion" => "Seychelles"],
            ["codigo_iso" => "SL", "descripcion" => "Sierra Leone"],
            ["codigo_iso" => "SG", "descripcion" => "Singapore"],
            ["codigo_iso" => "SK", "descripcion" => "Slovakia"],
            ["codigo_iso" => "SI", "descripcion" => "Slovenia"],
            ["codigo_iso" => "SB", "descripcion" => "Solomon Islands"],
            ["codigo_iso" => "SO", "descripcion" => "Somalia"],
            ["codigo_iso" => "ZA", "descripcion" => "South Africa"],
            ["codigo_iso" => "GS", "descripcion" => "South Georgia South Sandwich Islands"],
            ["codigo_iso" => "ES", "descripcion" => "Spain"],
            ["codigo_iso" => "LK", "descripcion" => "Sri Lanka"],
            ["codigo_iso" => "SH", "descripcion" => "St. Helena"],
            ["codigo_iso" => "PM", "descripcion" => "St. Pierre and Miquelon"],
            ["codigo_iso" => "SD", "descripcion" => "Sudan"],
            ["codigo_iso" => "SR", "descripcion" => "Suridescripcion"],
            ["codigo_iso" => "SJ", "descripcion" => "Svalbard and Jan Mayen Islands"],
            ["codigo_iso" => "SZ", "descripcion" => "Swaziland"],
            ["codigo_iso" => "SE", "descripcion" => "Sweden"],
            ["codigo_iso" => "CH", "descripcion" => "Switzerland"],
            ["codigo_iso" => "SY", "descripcion" => "Syrian Arab Republic"],
            ["codigo_iso" => "TW", "descripcion" => "Taiwan"],
            ["codigo_iso" => "TJ", "descripcion" => "Tajikistan"],
            ["codigo_iso" => "TZ", "descripcion" => "Tanzania, United Republic of"],
            ["codigo_iso" => "TH", "descripcion" => "Thailand"],
            ["codigo_iso" => "TG", "descripcion" => "Togo"],
            ["codigo_iso" => "TK", "descripcion" => "Tokelau"],
            ["codigo_iso" => "TO", "descripcion" => "Tonga"],
            ["codigo_iso" => "TT", "descripcion" => "Trinidad and Tobago"],
            ["codigo_iso" => "TN", "descripcion" => "Tunisia"],
            ["codigo_iso" => "TR", "descripcion" => "Turkey"],
            ["codigo_iso" => "TM", "descripcion" => "Turkmenistan"],
            ["codigo_iso" => "TC", "descripcion" => "Turks and Caicos Islands"],
            ["codigo_iso" => "TV", "descripcion" => "Tuvalu"],
            ["codigo_iso" => "UG", "descripcion" => "Uganda"],
            ["codigo_iso" => "UA", "descripcion" => "Ukraine"],
            ["codigo_iso" => "AE", "descripcion" => "United Arab Emirates"],
            ["codigo_iso" => "GB", "descripcion" => "United Kingdom"],
            ["codigo_iso" => "US", "descripcion" => "United States"],
            ["codigo_iso" => "UM", "descripcion" => "United States minor outlying islands"],
            ["codigo_iso" => "UY", "descripcion" => "Uruguay"],
            ["codigo_iso" => "UZ", "descripcion" => "Uzbekistan"],
            ["codigo_iso" => "VU", "descripcion" => "Vanuatu"],
            ["codigo_iso" => "VA", "descripcion" => "Vatican City State"],
            ["codigo_iso" => "VE", "descripcion" => "Venezuela"],
            ["codigo_iso" => "VN", "descripcion" => "Vietnam"],
            ["codigo_iso" => "VG", "descripcion" => "Virgin Islands (British)"],
            ["codigo_iso" => "VI", "descripcion" => "Virgin Islands (U.S.)"],
            ["codigo_iso" => "WF", "descripcion" => "Wallis and Futuna Islands"],
            ["codigo_iso" => "EH", "descripcion" => "Western Sahara"],
            ["codigo_iso" => "YE", "descripcion" => "Yemen"],
            ["codigo_iso" => "ZR", "descripcion" => "Zaire"],
            ["codigo_iso" => "ZM", "descripcion" => "Zambia"],
            ["codigo_iso" => "ZW", "descripcion" => "Zimbabwe"],
            ["codigo_iso" => "N/A", "descripcion" => "N/A"]
        ];

        $paises = array_map(function($paises) use ($now) {
           return [
               'descripcion' => strtoupper($paises['descripcion']),
               'codigo_iso' => $paises['codigo_iso'],
               'updated_at' => $now,
               'created_at' => $now,
           ];
        }, $paises);

        \DB::table('pais')->insert($paises);        

        /*foreach ($countries as $country) {
            App\Country::firstOrCreate($country);
        }*/
    }
}
